# Generated by Django 3.2.25 on 2024-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='current_step',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
